@startuml
component Controller <<view component>> as con
component Services <<logic component>> as ser
component Repository <<persistence>> as repo
database Database <<h2>> as data
component EmailSender <<external>> as mail
component Model <<model component>> as model

con --> ser
con --> model
ser --> repo
repo -0)- data
mail -r0)- ser
model -l-> ser
@enduml